# Site
title:              "Tecs | Grupo de comput{ação social} da USP"
bio:                'Um grupo de extensão universitária focado no impacto social da computação e da tecnologia formado por alunos da Universidade de São Paulo.'
description:        "Um grupo de extensão universitária focado no impacto social da computação e da tecnologia formado por alunos da Universidade de São Paulo."
locale:             pt_BR
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   tecs-usp

# Social
analytics-id:       "default"
facebook:           tecs.usp
medium:             tecs.usp
github:             tecs-usp
telegram:           tecsusp

# personal
location:           "Rua do Matão, 1010 - Vila Universitária, São Paulo, SP"
phone:              310-318-5555
email:              tecs@ime.usp.br

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
